import Head from "next/head";
import React from "react";
import Layout from "../../components/Layout";
import Navbar from "../../components/Navbar";
import Upload from "../../components/Upload";

const Admin = () => {
    return (
        <Layout>
            <Head>
                <title>E-Mediate - Admin</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar isLogout={true}/>
            <div className="h-screen grid place-items-center text-white text-5xl font-bold">
                <Upload />
            </div>
        </Layout>
    );
};

export default Admin;
