import Head from 'next/head'
import Layout from '../components/Layout'
import Navbar from '../components/Navbar'
import Search from '../components/Search'

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>E-Mediate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className='grid place-items-center h-screen font-mont'>
        <Search />
      </div>
    </Layout>
  )
}
